version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my-closet-api
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8.0.34
    environment:
      MYSQL_DATABASE: my-closet-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
    ports:
      - "3306:3306"