on: [push]
jobs:
  # "test_api"というジョブIDでジョブを定義
  test_api:
    name: test api
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0.34
        env:  
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3307:3307
    steps:
      - run: echo "The job was automatically triggered."
      - name: Checkout
        uses: actions/checkout@v4
      - run: sudo systemctl start mysql
      - run: docker-compose up -d
      - run: docker-compose run web python3 manage.py test my_closet_api_apps/tests/
  