on: [push]
jobs:
  # "test_api"というジョブIDでジョブを定義
  test_api:
    docker-compose:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      MYSQL_PWD: root

    steps:
      - run: echo "The job was automatically triggered."
      - name: Checkout
        uses: actions/checkout@v4
      - run: docker-compose up -d --wait
      - run: docker-compose run web python3 manage.py test my_closet_api_apps/tests/
  