on: [push]
jobs:
  # "test_api"というジョブIDでジョブを定義
  test_api:
    name: test api
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0.34
        env:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: root
    container:
      image: python:3.11
      env:
        MYSQL_HOST: db
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
    steps:
      - run: echo "The job was automatically triggered."
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          apt-get update && \
          apt-get -y install mariadb-client
      - run: ./requirements.txt /requirements.txt
      - run: pip install -r /requirements.txt
      - run: python3 manage.py test my_closet_api_apps/tests/
